### PR TITLE
Filter problem of accidental extra version increment

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1671

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov @jjohnstn 

I don't think the problems where relate to my changes.

**Comment by iloveeclipse** [comment]
> I don't think the problems where relate to my changes.

Surely not. Thanks Ed.

**Comment by iloveeclipse** [comment]
> @iloveeclipse I did see that there was a version bump and was going to comment but I also saw from @fedejeanne that it fixed the PR build error. Is there an issue with the PR version checking or was this just a hiccup?

The problem was real and Ed "fixed" it via API filter, thanks Ed!

Ideally one should rebase every PR before merging or check it locally on latest head to avoid such problems in the future.

**Comment by jjohnstn** [comment]
My bad for merging.  Thanks Ed.

**Pull request merged**
