### PR TITLE
Remove LTK bundles, migrating them to eclipse.platform.ui

### PR DESCRIPTION
**Pull request by mickaelistria**
## What it does

Removes LTK bundles once they are merged into Platform UI ( https://github.com/eclipse-platform/eclipse.platform.ui/pull/1197 )

## How to test

Having a I-Build working should be enough

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by rgrunber** [comment]
I assume you'd also have to synchronize 
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/jdtOptions.txt#L49-L50
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt#L5-L6

**Comment by mickaelistria** [comment]
Yes, although the help topics are covered by unit tests and can be contributed in a 2nd step without fully breaking the build. So I plan to first get a build, and then fix the doc.

**Review by rgrunber — APPROVED** [review]
Tried this out and seems fine to me. This removed the bundles, so if we're just relocating, the dependent bundles, they'll just be resolved from the target platform as opposed to the workspace itself.

**Comment by mickaelistria** [comment]
Thank you! I just triggered an I-Build to ensure things are not too broken.

**Pull request merged**
