### PR TITLE
Make Onboarding Icons smaller and look better in dark theme

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by BeckerWdf** [comment]
@vogella and @iloveeclipse: Can you pls. test?

**Comment by iloveeclipse** [comment]
Just noticed that browsing image contains some artifact that seem to be unneeded (was also before in the bigger image): 
image

**Comment by iloveeclipse** [comment]
The PR title looks wrong: "Make Onboarding Icons look better in dark theme" - has nothing to do with dark theme, but with image size.

**Comment by BeckerWdf** [comment]
> The PR title looks wrong: "Make Onboarding Icons look better in dark theme" - has nothing to do with dark theme, but with image size.

It also makes them better in dark theme - see the changes in the opacity of the fill color

**Comment by iloveeclipse** [comment]
> So I also took it over to this icon.

On 32x32 pixel there are only 2 pixels visible, which probably was never noticed.
But on a bigger size picture this element in background simply looks like a graphical design artifact (which it is most likely is?).

**Comment by iloveeclipse** [comment]
> > which it is most likely is?.
> 
> No it's not it's some kind of a hook. See here:
> 
> image

O. O-o. Well, not sure how good the resulting icon matches the original picture / idea of it, but for me in 300x300 size it looks like a bug :-)
@trancexpress : WDYT?

**Comment by BeckerWdf** [comment]
> > > which it is most likely is?.
> > 
> > 
> > No it's not it's some kind of a hook. See here:
> > image
> 
> O. O-o. Well, not sure how good the resulting icon matches the original picture / idea of it, but for me in 300x300 size it looks like a bug :-) @trancexpress : WDYT?

See #524

**Pull request merged**
