### PR TITLE
Push down code related to java partition scanners, now that o.e.jface…

### PR DESCRIPTION
**Pull request by robstryker**
….text.rules have been moved to org.eclipse.text

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by robstryker** [comment]
@jjohnstn  I noticed in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/992  that you didn't like me removing the api problem filter. 

The problem is, my patches continue to fail unless I remove the problem filter.  For example:  https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1011/2/consoleFull

```
15:41:25  [INFO] API Analysis finished in 19 s.
15:41:25  [INFO] 0 API ERRORS
15:41:25  [INFO] 1 API warnings
15:41:25  [WARNING] [API WARNING] File MANIFEST.MF at line 0: The API problem filter for: 'The minor version should be the same for version 1.21.0, since no new APIs have been added since version 1.20.0' is no longer used (location: /home/jenkins/agent/workspace/eclipse.jdt.ui-github_PR-1011/org.eclipse.jdt.core.manipulation/META-INF/MANIFEST.MF)
```

I'm sorry if I keep causing extra work by removing this filter, but the build basically keeps demanding it.  :|

**Comment by jjohnstn** [comment]
Hi @robstryker The time before I applied your patch and I got an error, but with this patch I am no longer setting the error.  Probably because you added the split in MANIFEST.MF so this time it is fine to remove.

**Comment by jjohnstn** [comment]
I did a review and I'm fine once it passes verification.  I will restart the build in case it is a spurious error.

**Comment by robstryker** [comment]
Thanks. I'm unable to replicate the test failure locally. Will keep my eye on it.

**Review by jjohnstn — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
