### PR TITLE
Fix the Java editor not saving HTML to Clipboard (#89)

### PR DESCRIPTION
**Pull request by mihnita**
## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

---

The original bug was filed here:
https://github.com/eclipse-platform/eclipse.platform.text/issues/101

Very likely that is the wrong place, but at the time I didn't know where the fix will end up.
Let me know if you want me to file an equivalent bug here (or close than one and open it here)

Thank you,
Mihai

### CODE REVIEW

**Comment by mihnita** [comment]
Gentle ping?

If this looks reasonable to you I will sync to the head and make sure it builds.
So that maybe have it in RC1?

Thank you,
Mihai

**Comment by jjohnstn** [comment]
Hi @mihnita this didn't make the M3 cut-off and it wouldn't get sufficient testing jammed into RC1 which is already built and being verified.  This will end up in 4.27 M1 as soon as the master branch is available for merging again.

**Comment by mihnita** [comment]
The wiki for [SimRel-2022-12](https://wiki.eclipse.org/Category:SimRel-2022-12) says (about `2022-12 RC1`):
> No new features and APIs after this date!

This is not a feature, it is a bug fix. And does not change any API.
The change is trivial: when copying styled text to the clipboard also copy HTML, in addition to plain text and RTF.
And the real "copy HTML" work is done by `StyledText`.

Also, I did the testing (as the initial checkbox says, "I have thoroughly tested my changes")

Thank you,
Mihai

**Comment by mihnita** [comment]
Note: this fix is also one of the visible part of this: [StyledText does not store the HTML format in the clipboard #85](https://github.com/eclipse-platform/eclipse.platform.debug/issues/85)
Which is in the N&N (https://www.eclipse.org/eclipse/news/4.26/platform_isv.php#SWT)

Being able to copy code and paste it in something like Google Slides is one of the main benefits of that feature.
But JDT seems to be its own thing for copy to clipboard (the code I'm changing).
So without it copy / paste C/C++ (or other code) will preserve the colors, Java code will not.

**Review by jjohnstn — APPROVED** [review]
LGTM.  I will add Roland as a second reviewer to see if this can be put into RC2.

**Comment by jjohnstn** [comment]
@rgrunber Please review this for possible inclusion into 4.26 RC2.

**Comment by jjohnstn** [comment]
Hi @iloveeclipse  What is your opinion about including this for RC2 in light of mihnita's comment above with this being tied to N&N feature?

**Comment by mihnita** [comment]
Thank you!
M.

**Review by noopur2507 — COMMENTED** [review]
Thanks, @mihnita for the fix and @jjohnstn for taking a look. The fix looks good and we can include it for RC2 as it is tied to the N&N entry. 

Please test it on all the platforms i.e. Windows, Linux, and macOS before releasing it for RC2.

**Comment by noopur2507** [comment]
@vogella Adding Lars for PMC approval for RC2.

**Comment by vogella** [comment]
+1 from PMC member

**Comment by jjohnstn** [comment]
> Thanks, @mihnita for the fix and @jjohnstn for taking a look. The fix looks good and we can include it for RC2 as it is tied to the N&N entry.
> 
> Please test it on all the platforms i.e. Windows, Linux, and macOS before releasing it for RC2.

I only have access to Linux.  @noopur2507 or @vogella can you help with Mac and Windows?

**Comment by jjohnstn** [comment]
I have verified this for Linux using the given test of copying some lines from the Java editor into Google slides and verifying the pasted lines have the editor colors where applicable.

**Comment by vogella** [comment]
I also can't test on Windows or Mac at the moment

**Comment by mihnita** [comment]
I have access to all 3 platforms.
I tested it before, but I can test it again over the weekend, with everything up to date.
Mihai

**Comment by mihnita** [comment]
Tested on Windows 11, MacOS, and Debian

Tested GMail, Google Docs, Google Slides in Firefox and Chrome
Tested MS Word 2000 and MS PowerPoint 2000 (Win only)
Tested LibreOffice Writer (~docs) and LibreOffice Impress (~slides) (Debian only)

Compared before and after, everything works as intended.

**Comment by jjohnstn** [comment]
@iloveeclipse The testing on Windows and MacOs is done by the submitter as no one else could help.  My vote is to accept this, as the change is simple, but it being RC2 I need either you or @noopur2507 to give final ok.

**Comment by noopur2507** [comment]
Thanks. Please release it for RC2.

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
Please rebase on master branch. I see there is a merge commit `Merge branch 'eclipse-jdt:master' into master`, that shouldn't be in git history!

**Comment by iloveeclipse** [comment]
I personally do not see the urgency to get it into RC2, so I "+-0" on this change.
Beside this I've tested the fix on RHEL 7.9, seem to work with Open Office.

**Comment by iloveeclipse** [comment]
> Please rebase on master branch. I see there is a merge commit `Merge branch 'eclipse-jdt:master' into master`, that shouldn't be in git history!

In the future: **never** work on master branch, neither in JDT nor elsewhere in the platform. Recommended is to work on dedicated branch, where the workflow is as simple as: "create branch, hack, commit, rebase if needed on master, push, change if asked on review, commit, rebase on master, push.

**Comment by iloveeclipse** [comment]
Here is what the current PR branch looks like (wrong):

image

and here how it should look like:

image

**Comment by mihnita** [comment]
Did a rebase, thanks,
Mihai

**Review by iloveeclipse — APPROVED** [review]

**Comment by mihnita** [comment]
Thank you very much everybody!
Mihai

**Pull request merged**
