### PR TITLE
Move CollectionsUtil to jdt.core.manipulations and add a utility clas…

### PR DESCRIPTION
**Pull request by robstryker**
…s for jface.util.Util.replaceAll to break UI dep

## What it does

This patch copies a single function from a JFace / ui bundle into org.eclipse.jdt.core.manipulations and makes current callers in jdt.ui's 'core refactor' folder use this class instead of depending on UI. This will help break the UI dependencies of this specific source folder and allow it to be moved down to a core bundle more easily in the near future. 

## Author checklist

- [X] I have thoroughly tested my changes
- [X] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [X] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Review by jjohnstn — COMMENTED** [review]
Looks fine, but for the new file you should use a 2023 copyright and add a note that logic was copied from: o.e.jface.util.Util.

**Comment by robstryker** [comment]
> Looks fine, but for the new file you should use a 2023 copyright and add a note that logic was copied from: o.e.jface.util.Util.

Looks like that's been done after your comment. Header says 2019,2023, and "Copied from" is there.

**Comment by jjohnstn** [comment]
> > Looks fine, but for the new file you should use a 2023 copyright and add a note that logic was copied from: o.e.jface.util.Util.
> 
> Looks like that's been done after your comment. Header says 2019,2023, and "Copied from" is there.

A new class has a new copyright (just 2023).  If you had just moved it with the same name, then you just update the last year.  The copied from should be in the copyright header as that explains everything where it is needed.  There you add a line with Red Hat or Red Hat Inc explaining the modifications you made (in this case just copied and renamed),

**Review by jjohnstn — APPROVED** [review]
Looks good

**Pull request merged**
