### PR TITLE
Fix clicking on a ParametrizedTest

### PR DESCRIPTION
**Pull request by gzsombor**
## What it does
When we click on the 'grouping' element for a ParametrizedTest, the code tries to find the method without the parameter types, but the search actually tries to find a parameter-less method with the same name.

## How to test

1. Have a JUnit test:
```
	@ParameterizedTest
	@ValueSource(ints = {1,2,3})
	void x(int l) {
		fail("Not yet implemented");
	}

	@ParameterizedTest
	@ValueSource(ints = {4})
	void y(int l) {
		fail("Not yet implemented");
	}
 
	@TestFactory
	Collection<DynamicTest> dynamicTestsWithCollection() {
		return Arrays.asList(DynamicTest.dynamicTest("First test", () -> {
			fail("Bad luck");
		}), DynamicTest.dynamicTest("Second test", () -> {
			fail("Bad luck");
		})
		);
	}

	@ParameterizedTest
	@MethodSource("testArgs")
	void testInvisibleCharacters(String msg) {
        }

	private static List<String> testArgs() {
		return List.of("aaa\u0000MISSING", "bbb\u0000MISSING");
	}


```
2. Run the tests, 
3. In the test results, try to click on `x(int)` or `y(int)`
4. A dialog came up complaining of the missing method, instead of navigating to the actual code.
5. Check that the test cases under `testInvisibleCharacters` shows as `aaa MISSING` and `bbb MISSING` instead of `aaa` and `bbb` 

## Author checklist

- [X] I have thoroughly tested my changes
- [X] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [X] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by akurtakov** [comment]
@jjohnstn Would you please review this one?

**Comment by jjohnstn** [comment]
@akurtakov Will do now.

**Review by jjohnstn — APPROVED** [review]
Looks fine.

**Comment by gzsombor** [comment]
Thanks!

**Pull request merged**
