### PR TITLE
[WIP] Additional of Bytecode outline into JDT

### PR DESCRIPTION
**Pull request by LunarLaurus**
## What it does

[Add Bytecode Outline to Eclipse JDT](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/364)
As discussed with Andrey, this is the initial work of implementing BCO into JDT.
This is currently a WIP, I can't seem to find how to get this code to actually launch, so any suggestions would be appreciated.
Please note that I have yet to format to JDT standards, plus have mistakenly uploaded a heap of useless files.
I will do these last after I figure out how to test and can then implement the other features noted in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/364. If squashing the commit history is not appropriate, I am happy to create a new PR once 100% completed.

## How to test

Unsure, Eclipse documentation for testing JDT isn't great.
Any advice is appreciated!

## Author checklist

- [?] I have thoroughly tested my changes
- [?] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [X] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by iloveeclipse** [comment]
```
Missing requirement: org.eclipse.jdt.bcoview 1.0.1.qualifier requires 'osgi.bundle; org.objectweb.asm.analysis 7.0.0' but it could not be found
```
This means, we need asm bundles below in the dependencies (currently only asm and asm.tree are available).

- org.objectweb.asm.analysis
- org.objectweb.asm.commons
- org.objectweb.asm.util

**Comment by LunarLaurus** [comment]
@iloveeclipse They do seem to be defined in bcoview.MANIFEST.MF.
```
 org.objectweb.asm;bundle-version="7.0.0",
 org.objectweb.asm.tree;bundle-version="7.0.0",
 org.objectweb.asm.analysis;bundle-version="7.0.0",
 org.objectweb.asm.commons;bundle-version="7.0.0",
 org.objectweb.asm.util;bundle-version="7.0.0",
```

Is there somewhere else they should be?

**Comment by iloveeclipse** [comment]
> Is there somewhere else they should be?

I assume in some magic maven / tycho pom commands. If not there, we need them in the platform (SDK) first.

**Comment by akurtakov** [comment]
Tycho resolves dependencies from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target so you would have to add them there. I see this patch uses asm 7.x while asm 9.x is used through out the eclipse codebase so it might be best to align too.

**Comment by iloveeclipse** [comment]
> I see this patch uses asm 7.x while asm 9.x is used through out the eclipse codebase so it might be best to align too.

That just sets *minimal* range, but yes, it can be lifted up if inside SDK.

> Tycho resolves dependencies from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target

OK, so I will provide a PR for that.

**Comment by LunarLaurus** [comment]
Shall I wait for your PR then @iloveeclipse ?

I just wish I could figure out how to set up a proper development environment.
Oomph seems to break and I have to use the workaround here [Bug in Oomph](https://bugs.eclipse.org/bugs/show_bug.cgi?id=566700).

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/809.
Looks like we had almost all asm bundles except asm-analysis.

> Shall I wait for your PR then

Once asm will be there I would like to re-create this PR by myself - don't get me wrong, but I think that's my responsibility as code owner :-)

I will push your pom changes on top in extra commit.
And once the basic **current** BCO code is there, you could continue if you like with extra improvements (editor replacement etc).

**Comment by LunarLaurus** [comment]
Thank you! I am more than happy to continue with the additional features.
Hopefully this will make plugin development easier. :)

**Comment by LunarLaurus** [comment]
I will close this for now. 👍

**Comment by iloveeclipse** [comment]
Follow up: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/385

**Pull request closed without merging**
