### PR TITLE
Bug 572440 - combine declaration and overridden assignment

### LINKED ISSUE #1330: Bug 572440 - [cleanup] Combine declaration and assignment of local variable during "Remove overridden assignment"
From: https://bugs.eclipse.org/bugs/show_bug.cgi?id=572440

==============================================================================================

Looking at https://git.eclipse.org/r/c/jdt/eclipse.jdt.debug/+/171078 it would be nice to have a clean-up which combines declaration and assignment of a local variable if both happen in two lines:

-----
Before:
BuildCommand result;
result = (BuildCommand) super.clone();
	
After:
BuildCommand result = (BuildCommand) super.clone();
------

IMHO this improves readability.

====================================================================================================

A further comment mentions that this functionality should be incorporated into "Remove overridden assignment".

### PR DESCRIPTION
**Pull request by jjohnstn**
- treat variable declarations that have no initializer the same as ones that do for the first declaration that gets overridden
- add new test to CleanUpTest
- fixes #1330

## What it does

See issue.

## How to test

See new test or bug or issue.

## Author checklist

- [X] I have thoroughly tested my changes
- [X] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [X] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by jjohnstn** [comment]
@vogella This is an enhancement you asked for a number of years ago.  Originally you just wanted to combine a declaration with an assignment right after it.  I modified the code so that a declaration without an initializer was treated the same as one with an initializer so it will combine even if not directly together.  Any problems with that or do you only want if they are directly together?

**Comment by jjohnstn** [comment]
@vogella After thinking about it a bit, I'm going to change it back to your original proposal of just the immediate statement after the declaration since some users may want all declarations up top but have the assignments close to where they are used for clarity.

**Comment by vogella** [comment]
@jjohnstn hey, thank you for this. Also your memory is impressive (that you remember that I suggested that). It is very nice to see that this will be available soon

**Comment by jjohnstn** [comment]
> @jjohnstn hey, thank you for this. Also your memory is impressive (that you remember that I suggested that). It is very nice to see that this will be available soon

My memory isn't that impressive :)  Thank Bugzilla stale bug reminder e-mails.  Not sure if there is something similar for github.

**Pull request merged**
