### PR TITLE
CopyQualifiedNameAction: never copy file eclipse.platform#372

### PR DESCRIPTION
**Pull request by jukzi**
## What it does
Only copy the name when the user asks for that.

## How to test
"copy qualified name" from package explorer of any file, paste to Teams/Word

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions]
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Review by jjohnstn — APPROVED** [review]
Seems reasonable, but as mentioned, this has been around for quite a while.  Last change to the code was 2010.  Let's get it into 4.28 M1 to see if there is a lot of dependency on the bad behavior,

**Comment by jjohnstn** [comment]
@jukzi In the future, if you need to reference issues from another component that a PR fixes, it is helpful to include the entire URL of the issue.

**Comment by jukzi** [comment]
ok, thanks @jjohnstn

**Comment by jukzi** [comment]
https://github.com/eclipse-platform/eclipse.platform/issues/372

**Pull request merged**
