### PR TITLE
Recommend variable name for Extracted Local Variable Refactoring when the extracted expression is a method invocation

### PR DESCRIPTION
**Pull request by Michaelll123**
## What it does
see  issue #684 
## How to test
run test161.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by jjohnstn** [comment]
Hi @Michaelll123 Please rename the tests as they now conflict with tests you just added and do a rebase (not merge) from origin/master so the patch will build.  I'll try to review this for 4.30 M1 if you can get this turned around in time.

**Comment by Michaelll123** [comment]
> Hi @Michaelll123 Please rename the tests as they now conflict with tests you just added and do a rebase (not merge) from origin/master so the patch will build. I'll try to review this for 4.30 M1 if you can get this turned around in time.

will do today.

**Review by jjohnstn — APPROVED** [review]
Looks good, thanks

**Pull request merged**
