### PR TITLE
Suppress deprecation: java.util.Observable

### PR DESCRIPTION
**Pull request by jukzi**
There is no plan to change the implementation

### CODE REVIEW

**Comment by jukzi** [comment]
jenkins did not find the reference on master:
```
10:47:02  [ReferenceFinder] [-ERROR-] Errors while computing the reference build:
10:47:02  [ReferenceFinder] [-ERROR-] -> no job found for target branch 'master' (is the branch correctly defined?)
10:47:02  [ReferenceFinder] Configured reference job: 'eclipse.jdt.ui-github/master'
10:47:02  [ReferenceFinder] There is no such job - maybe the job has been renamed or deleted?
10:47:02  [ReferenceFinder] Found a `MultiBranchProject`, trying to resolve the target branch from the configuration
10:47:02  [ReferenceFinder] -> no target branch configured in step
10:47:02  [ReferenceFinder] -> detected a pull or merge request for target branch 'master'
```

**Comment by jukzi** [comment]
@akurtakov where is the jenkins build for jdt.ui master?
image

**Comment by jukzi** [comment]
> where is the jenkins build for jdt.ui master?

@iloveeclipse @ktatavarthi any idea, i don't know how/where those jobs are configured?

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1157/2/

**Comment by akurtakov** [comment]
Comparing jdt.core(https://ci.eclipse.org/jdt/job/eclipse.jdt.core-github/indexing/console) and jdt ui(https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/indexing/console) points that jdt.ui is missing :
```
Checking branch [master](https://github.com/eclipse-jdt/eclipse.jdt.core/tree/master)

  Getting remote pull requests...
      ‘Jenkinsfile’ found
    Met criteria
```
and continues to the next branch. Aka there is no valid Jenkinsfile in master branch and thus Jenkins is not building it . Most likely some recent change to the file made it invalid.

**Comment by akurtakov** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1148/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8L30 lacks closing ] symbol(s) makes the file invalid.

**Comment by jukzi** [comment]
no, the problem is there is no job "master" on the jdt.ui jenkins:
https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-Github/job/master/

**Comment by akurtakov** [comment]
> no, the problem is there is no job "master" on the jdt.ui jenkins: https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-Github/job/master/

Seems like you know better what's wrong .

**Comment by laeubi** [comment]
The Jobs are created automatically unless otherwise configured (I can't see the job config...)

**Comment by jukzi** [comment]
jdt.ui has like 100 branches, but only a dozen builds, what makes a branch to have a jenkins job?
https://github.com/eclipse-jdt/eclipse.jdt.ui/branches/all

**Comment by jukzi** [comment]
i created a ticket: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4243

**Comment by akurtakov** [comment]
@iloveeclipse Is it ok to delete all BETA_JAVAXX branches for pre Java 21 ? These branches are long time merged in master and getting less unused things scanned by Jenkins https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/indexing/console might help in spotting issues.

**Comment by jukzi** [comment]
> I have reset my fork to not contain latest change in Jenkinsfile

I wonder if that change is really related, as debug and core still have their master.
What happens if you use HEAD instead? and what if HEAD+revert of Jenkinsfile?

**Comment by akurtakov** [comment]
https://ci.eclipse.org/jdt/job/akurtakov-eclipse.jdt.ui-github/ has upstream_master which is same as master of this repo and is found - aka that theory seems to be wrong.

**Comment by akurtakov** [comment]
So https://stackoverflow.com/questions/51270985/jenkins-multi-branch-pipeline-missing-a-branch points that https://stackoverflow.com/questions/51270985/jenkins-multi-branch-pipeline-missing-a-branch might be causing it:
```
This was particularly confusing and annoying when develop vanished in Jenkins just because a PR from develop to master was open. The behaviour can be changed in the job settings.
```
As this is effort to merge branch to master.

**Comment by akurtakov** [comment]
Just when I went to try it webmaster figured the same too https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4243#note_1706550 . 
@noopur2507 Is the branch and these merges really needed ? I don't see anything that needs to be done in a branch as @mpalat and @jarthana already agreed at https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1703#issuecomment-1848435241

**Pull request merged**
