### PR TITLE
Add Bytecode Outline view to JDT UI

### PR DESCRIPTION
**Pull request by iloveeclipse**
See
- https://github.com/iloveeclipse/bytecodeoutline/issues/8
- https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/364

### CODE REVIEW

**Comment by akurtakov** [comment]
You're using wrong bundle name "org.objectweb.asm.analysis" but if you look at https://repo1.maven.org/maven2/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar upstream uses "org.objectweb.asm.tree.analysis" . It would be best to use import-package instead IMHO.

**Comment by iloveeclipse** [comment]
OK, the build works, thanks to hint from @akurtakov. But in order to be in the SDK, the bundle need to be added to the JDT UI feature, right?

**Comment by akurtakov** [comment]
It has to be added to some feature in order to end up in the p2 repo and/or zips. It's a separate question whether this one and https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/387 should be installed by everyone that installs JDT.

**Comment by akurtakov** [comment]
IMHO merge it in the build and tackle publishing separately. Also doesn't this one needs CQ to get in?

**Comment by iloveeclipse** [comment]
Bytecode view is useful for anyone who wants understand **how** Java code is actually compiled and works, independently from JDT. 

So it is of general use for Java development. #387 is indeed interesting only for JDT development.

One can see that there are some people interested in that: https://marketplace.eclipse.org/content/bytecode-outline

image

**Comment by iloveeclipse** [comment]
> IMHO merge it in the build and tackle publishing separately.

OK

> Also doesn't this one needs CQ to get in?

This would be another question. How one could start that? The original repo is: https://github.com/iloveeclipse/bytecodeoutline

**Comment by akurtakov** [comment]
> > Also doesn't this one needs CQ to get in?
> 
> This would be another question. How one could start that? The original repo is: https://github.com/iloveeclipse/bytecodeoutline

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/new?issuable_template=vet-project

**Comment by iloveeclipse** [comment]
> > > Also doesn't this one needs CQ to get in?

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6368

**Comment by iloveeclipse** [comment]
> > > > Also doesn't this one needs CQ to get in?
> 
> https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6368

@akurtakov : the issue was closed as approved **without further comments**.

image

I assume this means OK?

**Comment by akurtakov** [comment]
Yes, as long as it's APPROVED we are safe to go.

**Pull request merged**
