### PR TITLE
Bug #237: No comparison dialog for subclasses of ComparisonFailure in JUnit5

### LINKED ISSUE #237: No comparison dialog for subclasses of ComparisonFailure in JUnit5
Subclasses of `ComparisonFailure` do not benefit from the comparison dialog in JUnit5. It looks like it might have been [this fix for Bug 538956: [JUnit 5] Incorrect JUnit 5 test results without JUnit 4 on the classpath](https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/8bff492a738ed1c08ecf857fd77e1fad38c06fad#diff-b8dd354caa0771bd3282216124abf47badb8b8d18e1151e9c5d9034b336c17a1L133-R149) that broke it.

### PR DESCRIPTION
**Pull request by dpetroff**
## What it does
Fixes #237 

## How to test
Throw a __subclass__ of `ComparisonFailure` from a JUnit5 test and see that the compare dialog works for it.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by dpetroff** [comment]
I suppose it was a bit optimistic of me to use streams for that... Fine, I'll do it oldschool.

**Review by jjohnstn — APPROVED** [review]
Looks fine.  Will have to wait until master repo is open for 4.26 M1 to merge.

**Comment by dpetroff** [comment]
Not sure how to retrigger the workflow. Also, what kind of ETA can I expect for this making it into eclipse "check for updates" and the automatic updates via eclipse setup tasks after it's merged? I'd be happy to do a downbranch PR as well if that means it gets there sooner.

**Comment by jjohnstn** [comment]
Hello @dpetroff the regular "check for updates" will not find this fix until 4.26 is released.  The fix will be part of the daily I-builds and the 4.26 milestones: M1, M2, M3, RC1, and RC2.  You can point to the 4.26 I-builds via: https://download.eclipse.org/eclipse/updates/4.26-I-builds

**Pull request merged**
