### PR TITLE
Fix while loop to enhanced for loop conversion issue with EntrySet github issue 109

### PR DESCRIPTION
**Pull request by carstenartur**
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/109

	public static void before() {
		Map<String, Object> map = Map.of("Hello", new Object());
		Iterator<Entry<String, Object>> iterator = map.entrySet().iterator();
		while (iterator.hasNext()) {
			Entry<String, Object> entry = iterator.next();
			System.out.println(entry);
		}
	}

	public static void after() {
		Map<String, Object> map = Map.of("Hello", new Object());
		for (Entry<String> entry : map.entrySet()) {
			System.out.println(entry);
		}
	}

In this case the Entry<String> is wrong and should be Entry<String,Object>

## What it does
The code now considers a more complex case Entry<String,Object>

## How to test
Run the junit test case or a code sample as given above where loop if over a map.entrySet()

## Author checklist

- I have thoroughly tested my changes
- The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by carstenartur** [comment]
Hi @jjohnstn , Hi @HannesWell ,
for the first part of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/109 this patch might be a solution.
Feel free to give it a try.
Best regards,
Carsten

**Comment by jjohnstn** [comment]
Thanks Carsten.  It does solve the While loop issue.  I have enhanced the patch to handle nested parameterized types (e.g. Map<List<String>, Object>).  The other issues are for the old for iterator loop fix code.

**Comment by HannesWell** [comment]
Great, thank you both!
I'll try it again as soon as it is available with the new I-Build.

**Comment by HannesWell** [comment]
I just tested this fix and it worked well for maps with simple types and types that themself are parameterized with generic arguments.

But unfortunately it still fails with array types:

```
Map<Date[], Date[]> map = Map.of(new Date[0], new Date[1]);
Iterator<Entry<Date[], Date[]>> iterator = map.entrySet().iterator();
while (iterator.hasNext()) {
	Entry<Date[], Date[]> entry = iterator.next();
	System.out.println(entry);
}
```
Should be converted to
```
Map<Date[], Date[]> map = Map.of(new Date[0], new Date[1]);
for (Entry<Date[], Date[]> entry : map.entrySet()) {
	System.out.println(entry);
}
```
but is converted to
```
Map<Date[], Date[]> map = Map.of(new Date[0], new Date[1]);
for (Entry<> entry : map.entrySet()) {
	System.out.println(entry);
}
```

If generics and arrays are mixed
```
Map<List<Date[]>, Date[]> map = Map.of(List.of(), new Date[1]);
Iterator<Entry<List<Date[]>, Date[]>> iterator = map.entrySet().iterator();
while (iterator.hasNext()) {
	Entry<List<Date[]>, Date[]> entry = iterator.next();
	System.out.println(entry);
}
```
becomes
```
Map<List<Date[]>, Date[]> map = Map.of(List.of(), new Date[1]);
for (Entry<List<>> entry:map.entrySet()){
	System.out.println(entry);
}
```

Or the other ways round, Array of a generic type (although this is not warning free):
```
Map<List<String>[], Date[]> map = Map.of(new List[0], new Date[1]);
Iterator<Entry<List<String>[], Date[]>> iterator = map.entrySet().iterator();
while (iterator.hasNext()) {
	Entry<List<String>[], Date[]> entry = iterator.next();
	System.out.println(entry);
}
```
is falsely cleaned up to
```
Map<List<String>[], Date[]> map = Map.of(new List[0], new Date[1]);
for (Entry<> entry : map.entrySet()) {
	System.out.println(entry);
}
```

I suspect that in the just added addGenericTypes() method the case `typeArgument instanceof ArrayType` is missing (not sure if the class is named ArrayType, but I mean an array type).

**Comment by jjohnstn** [comment]
Yes, the addGenericTypes() method needs support for ArrayType.  Working on it.

**Comment by jjohnstn** [comment]
I have removed the addGenericTypes() method.  There is a more straight-forward way to set the type which I got from the older iterator-for-loop code.  It doesn't require building the type.

**Comment by HannesWell** [comment]
> I have removed the addGenericTypes() method. There is a more straight-forward way to set the type which I got from the older iterator-for-loop code. It doesn't require building the type.

That worked well, I just re-run the clean up on Equinox. Thank you.

**Pull request merged**
