### PR TITLE
AnnotateAssistTest1d8 test failed

### PR DESCRIPTION
**Pull request by stephan-herrmann**
addresses the ClassCastException

fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/736

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@iloveeclipse @jjohnstn  From 3 attempts I got 2 timeouts (and one unrelated intermittent failure).

Who decides about the timeout? It seems that the current limit of 40 min. is not realistic.

**Comment by iloveeclipse** [comment]
> Who decides about the timeout? It seems that the current limit of 40 min. is not realistic.

See 
https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/690340fdd53a50e5050c77a423dcc857c2b6f7ba/Jenkinsfile#L3

**Comment by stephan-herrmann** [comment]
> > Who decides about the timeout? It seems that the current limit of 40 min. is not realistic.
> 
> See
> 
> https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/690340fdd53a50e5050c77a423dcc857c2b6f7ba/Jenkinsfile#L3

Thanks, so the timeout has been at 40 since @ktatavarthi created that file 2 years ago (https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1)

Asked differently: does everybody think this is the right threshold?

**Comment by akurtakov** [comment]
Looking at https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/master/buildTimeTrend - normal build is usually around ~25 minutes. What we see is probably related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4063#note_2472456 . Meanwhile it should be fine to bump it to e.g. 60 minutes (twice slower than average time) so people don't have to restart builds like that.

**Comment by stephan-herrmann** [comment]
> Looking at https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/master/buildTimeTrend - normal build is usually around ~25 minutes. What we see is probably related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4063#note_2472456 . Meanwhile it should be fine to bump it to e.g. 60 minutes (twice slower than average time) so people don't have to restart builds like that.

Thanks, will do if/when I run into this problem again in the near future :)

**Pull request merged**
