### PR TITLE
Test merge action check

### PR DESCRIPTION
**Pull request by laeubi**
lets see what happens @iloveeclipse

### CODE REVIEW

**Comment by laeubi** [comment]
grafik

**Comment by trancexpress** [comment]
Looks great, thanks!

**Comment by trancexpress** [comment]
Looks great, thanks! Can you mention using rebase instead of merging as part of the error message (that is seen when clicking "Details")?

**Comment by laeubi** [comment]
grafik

**Comment by trancexpress** [comment]
Great!

**Comment by iloveeclipse** [comment]
@laeubi : great. Is there a way to run this action first and don't run jenkins build if action reports an error, to avoid that PRs block shared resources (nodes) with tests?

**Comment by laeubi** [comment]
It could block Github runs probably but Jenkins would be a bit more complicated.

If this is really crucial, one could enhance the Jenkinsfile to perform such checks but it will require setup of credentials and a like so it is a bit bigger task, 

Maybe one can archive something similar with some git magic:
https://stackoverflow.com/questions/74096323/get-origin-master-and-pr-commit-id-in-jenkins

but maybe it does not occurs that much often and test-results are still valuable for a "mergecommited" one?

**Comment by iloveeclipse** [comment]
Ok, I think we can close this PR now.

**Pull request closed without merging**
