### PR TITLE
Move refactoring contribution extensions to jdt.core.manipulation

### PR DESCRIPTION
**Pull request by robstryker**
… also small error checks

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by robstryker** [comment]
@jjohnstn  This weekend, it was revealed that moving these extension point contributions down to jdt.core.manipulations led to many many strange and innaccurate API errors. Specifically, the api tools starts complaining about 100+ missing files (that are not  missing at all, have not been deleted, and also have not even been moved at all.) 

We may need to figure out how to run a build and skip the api tools for this specific patch? I don't think making a hundred problem filters for files that have not been deleted or moved is appropriate.

**Comment by iloveeclipse** [comment]
> it was revealed that moving these extension point contributions down to jdt.core.manipulations led to many many strange and innaccurate API errors. Specifically, the api tools starts complaining about 100+ missing files (that are not missing at all, have not been deleted, and also have not even been moved at all.)

@robstryker : as I wrote on https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/919#issuecomment-1806510014, it's tycho problem, see https://github.com/eclipse-tycho/tycho/issues/3019

There was a change in tycho that forces all bundles to define output paths in build.properties if they use API tooling, just see comments on linked issue.

**Review by jjohnstn — APPROVED** [review]
Looks good.

**Review by rgrunber — APPROVED** [review]
It's a +1 from me (assuming this is needed for the RC1 cycle)

Looking at https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ltk.core.refactoring/src/org/eclipse/ltk/internal/core/refactoring/history/RefactoringContributionManager.java#L164 , the contributions are still provided under the same namespace & id so there should be no noticeable difference. Also jdt.core.manipulation is guaranteed to be present where jdt.ui would be present so there's no way these would be missing.

@jjohnstn feel free to merge, though maybe a squash of the 2 commits beforehand.

**Comment by iloveeclipse** [comment]
-1 from me to merge.
Such kind of changes is not for RC1.
It is not a critical bug and not a recent regression.
Please wait for 4.31 M1.

**Comment by jjohnstn** [comment]
Just to clarify.  I was assuming this was for 4.31 M1.

**Comment by iloveeclipse** [comment]
There is an API error caused by this PR:
`The minor version should be the same for version 1.21.0, since no new APIs have been added since version 1.20.0`

https://download.eclipse.org/eclipse/downloads/drops4/I20231128-1800/apitools/analysis/html/org.eclipse.jdt.core.manipulation/report.html

Since we can't undo published version (it was already in the I Build), please add API filter or propose a PR that actually changes API :-)

**Pull request merged**
