### PR TITLE
Adds downloaded to the spellchecker

### PR DESCRIPTION
**Pull request by vogella**
The word "downloaded" should also be included in our spellchecker list.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by vogella** [comment]
@jjohnstn can you review?

**Review by jjohnstn — APPROVED** [review]
Looks fine.  I will do a rebase to get the build passed.

**Pull request merged**
