### PR TITLE
Jenkinsfile: fix wrong referenceBuild

### PR DESCRIPTION
**Pull request by jukzi**

### CODE REVIEW

**Comment by jukzi** [comment]
just another try...

**Comment by jukzi** [comment]
@laeubi @akurtakov @iloveeclipse anybody has seen an jenkins error like this before?
```
11:15:02  [INFO] --- dependency:3.6.1:copy (copy) @ org.eclipse.jdt.ui.examples.projects ---
Creating placeholder flownodes because failed loading originals.
ERROR: Cannot resume build because FlowNode 36 for FlowHead 1 could not be loaded. This is expected to happen when using the PERFORMANCE_OPTIMIZED durability setting and Jenkins is not shut down cleanly. Consider investigating to understand if Jenkins was not shut down cleanly or switching to the MAX_SURVIVABILITY durability setting which should prevent this issue in most cases.
[GitHub Checks] GitHub check (name: Jenkins, status: completed) has been published.
```

**Comment by iloveeclipse** [comment]
See https://community.jenkins.io/t/error-cannot-resume-build-because-flownode-19/9477

**Comment by jukzi** [comment]
this changed makes go "new ecj warnings" go away when master is unstable due to ecj warnings

image

```
Obtaining reference build from reference recorder
-> Found 'eclipse.jdt.ui-github » master #25'
Using reference build 'eclipse.jdt.ui-github/master #24' to compute new, fixed, and outstanding issues
Issues delta (vs. reference build): outstanding: 5, new: 0, fixed: 0
Evaluating quality gates
-> PASSED - Delta (any severity): 0 - Quality Gate: 1

```
 -master builds are still unstable
image

the ecj plugin now chooses the last - even unstable - build as reference. But not the failed one (master currently also suffers from the node error)
https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/master/25/console

**Pull request merged**
