### PR TITLE
[23] Markdown doc comments with codeblock don't parse Javadoc tags afterwards #2989

### PR DESCRIPTION
**Pull request by jarthana**
Test case for the jdt.core fix

## What it does
Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2980

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by jarthana** [comment]
The build failed because the new unstable I builds are not yet part of the composite. Will check once again tomorrow.

**Comment by akurtakov** [comment]
> The build failed because the new unstable I builds are not yet part of the composite. Will check once again tomorrow.

There will be I-build published until https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2358 is resolved.

**Comment by jarthana** [comment]
> > The build failed because the new unstable I builds are not yet part of the composite. Will check once again tomorrow.
> 
> There will be no I-build published until [eclipse-platform/eclipse.platform.releng.aggregator#2358](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2358) is resolved.

I recall @mpalat mentioning in an offline discussion that the the changes are expected and we should touch the affected bundles to proceed. But I will wait for him to update the relevant issue once he is sure. This particular issue can wait.

**Comment by mpalat** [comment]
> I recall @mpalat mentioning in an offline discussion that the the changes are expected and we should touch the affected bundles to proceed. But I will wait for him to update the relevant issue once he is sure. This particular issue can wait.

I guess no comment required here now as that issue is fixed :). Thanks @jarthana for waiting.

**Pull request merged**
