### PR TITLE
Add styling enhancements to signatures (JavaElementLinks) in Javadoc. Fixes #1073

### LINKED ISSUE #1073: Hard to read method signatures in Javaodc views
Hello

as per [advice](https://www.eclipse.org/lists/jdt-dev/msg02304.html) via JDT mailing lists, I'm creating this issue to have a place to discuss my proposal for improvements to JavaDoc content styling and it's implementation.

### Problem I'm addressing
Hard to read method signatures in JavaDoc views, for example:
javadoc_current

### Enhancements proposal & prototype
My prototype changes the presentation into IMHO more readable format, example:
javadoc_new
javadoc_new_colored

New enhancements are fully configurable (when to apply them, what colors to use):
preview_overlay

### More info
Can be found at [Eclipse JDT forums topic](https://www.eclipse.org/forums/index.php?t=msg&th=1114002&goto=1862222&#msg_1862222) I created to communicate goals, approach, decisions taken and progress.

### Requesting
I would like to have somebody, preferably with some level of decision making weight in JDT codebase / project, to evaluate my prototype and provide feedback so that I can finalize it and hopefully have it accepted eventually.

### PR DESCRIPTION
**Pull request by RedeemerSK**
## What it does
Adds various enhancements to styling / formatting of signatures in Javadoc presentation (HTML-based) views:
- togglable text wrapping (method parameters, generics type parameters used in method)
- togglable text formatting (generics type parameters used, method parameter names, method name, method class)
- togglable generic type parameters references text coloring
- togglable generic type parameters nesting levels text coloring
- togglable enhancement states: OFF / always ON / ON only on mouse hover over new styling button
- toggable enhancements state preferences saved separately for Javadoc hover view and Javadoc view, color preferences are shared
- styling button also acts as a menu where all aspects of enhancements can be configured : togglable states, color preferences
- defines 4 default colors for type parameters references / levels coloring, further references / levels re-use them repratedly by default
- supports Dark mode (theme) by defining separate default colors and gracefully handling switching themes

Examples:
Default enhancements:
javadoc_new
When hovered on styling button
javadoc_new_colored

Defaults for colors:
lightMode-colors-withFormatting
darkMode-colors-withFormatting

Changing settings example:
preview_overlay

colorPreferencesSubmenu-6colors
colorPreferencesSubmenu-0colors

See [Eclipse JDT forums topic](https://www.eclipse.org/forums/index.php?t=msg&th=1114002&goto=1862222&#msg_1862222) I created to communicate goals, approach, decisions taken and progress.

## How to test
At this stage of WIP prototype:
Have Javadoc for various Java source code elements displayed in both Javadoc hover (viewer) and Javadoc view. Interact with new styling menu button (added to toolbars) to form assumptions about what new visual items do & see if things then behave as one expects them to behave. 

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

Changes are currently WIP and thus at this stage not meant for thorough code-review, but rather for other people to be able to try them and provide feedback & future code-reviewer to have a look at how changes are  implemented.

### CODE REVIEW

**Comment by akurtakov** [comment]
Is this one still WIP as the title says? I guess so as it's not building and test are not passing. This is the minimum to be done before the patch can be considered seriously.

**Comment by RedeemerSK** [comment]
> Is this one still WIP as the title says? I guess so as it's not building and test are not passing. This is the minimum to be done before the patch can be considered for review.

Failing tests are fixed now. This PR is labeled WIP since the nature of my changes (enhancements) is such that I would first like to get some feedback from other peson / people on current prototype before requesting actual merge.

**Comment by RedeemerSK** [comment]
## List of enhancements:

### Formatting enhancements:
1. method name is made to visually stand out by highest CSS font-weight
2. method qualifier (encompassing class) is made to visually less significant by lowering CSS opacity
3. method return type is made to visually stand out by making text italic
4. method parameters names are made to visually stand out by making text italic
5. generic type parameters are made visually less significant by lowering CSS font-weight
6. opening '<' and closing '>' of generic type parameters sections are made to visually stand-out by highest CSS font-weight
7. opening '<' of nested generic type parameters sections are offset by single space
8. 1st method parameter is offset by space (not effective when wrapping enhancement is enabled as well)
### Wrapping enhancements:
1. method parameters are displayed on separate lines
2. prepended method generic type parameters are displayed on separate 1st line, therefore following method qualified + method name are displayed on separate line
### Type parameters references coloring enhancements:
1. each unique type parameter / class (if type is bound) can be collored with different configurable color
2. there are default colors for first 4 unique references, 1st and 2nd default color re-used for more
3. light theme and dark theme have different default colors
4. color defaults and preferences are shared with type parameters (nesting) levels coloring enhancements
### Type parameters (nesting) levels coloring enhancements:
1. each unique type parameters nesting level can be collored with different configurable color
2. there are default colors for first 4 levels, 1st and 2nd default color re-used for more
3. light theme and dark theme have different default colors
4. color defaults and preferences are shared with type parameters references coloring enhancements



# To notice / consider / think about
Things that I would like to point out to have somebody else to notice & think about:

1. default preferences for both Javadoc hover & view: formatting ON / wrapping ON/ type parameters references coloring ON_HOVER / type parameters (nesting) levels coloring OFF
5. enhancements toggling could be done also when hovering (somewhere) inside the Javadoc content itself, but I kept it just when hovering over new styling button in toolbar
6. should we be worried about this being the 1st place to have names of classes uniquely colored ? may it later cause unreasonable expectations / requests by the users regarding other places (e.g code editor) ?
10. type parameters (nesting) levels coloring - do you think it's justified to keep it included as it may be eventually used by some users ?
11. for icons I re-used existing ones that I found most fitting
12. there are color defaults for first 4 colors, if more are needed, 1st and 2nd are re-used repeatedly (alternating for odd / even) unless configured manually
13. suggestion for better colors ?
14. new toolbar button acts as A) hover target to enable enhancements with hover-only preference B) way to show configuration  menu - I tried to keep visual changes to UI widgets to mininum
15. all aspects of enhancements are fully configurable in the configuration menu, I avoided adding Eclipse (JDT) preferences pages completely
16. Javadoc view and Javadoc hover viewer have their own preferences for state of enhancements, but share colors preferences
17. Javadoc hover viewer has new toolbar button "aligned to right"
18. Javadoc hover viewer has another new button added aligned to right - it's temprary for debugging purposes and will be removed
19. Colors Preferences sub-menu presents all colors for which colors are configured as menu items - either by default or manually
20. Colors Preferences sub-menu presents colors currently used in content as enabled menu items and possible to change
21. Colors Preferences sub-menu presents colors currently nbot used in content as diasabled menu items
22. Styling menu button is disabled when Javadoc view is not currently displaying any content

**Comment by RedeemerSK** [comment]
I don't have access to MacOS so I can't test it on that platform. So if there's anyone willing to do that, it would be greatly appreciated.

For Linux, I am testing on native Ubuntu 22.04.3 LTS. After fully implementing required behavior of added GUI widgets on Windows, it all seems to work exactly the same also on Linux ... to my surprise, since I expected SWT may behave slightly different when it comes to when and which events are dispatched.

**Comment by RedeemerSK** [comment]
@akurtakov do you by chance have any feedback / opinion about the prototype ?
thanks in advance

**Comment by stephan-herrmann** [comment]
I like the idea. Have you also considered type annotations in signatures? This would be particularly interesting in the context of null annotations where implicit annotations (from `@NonNullByDefault` or from external annotations) are visualized in those hovers, too.

**Comment by jukzi** [comment]
i gave this PR a try: The superbold text looks blury and hard to read :-(, otherwise it looks OK and all tests pass.
image
Please also state some examples in JDK or eclipse workspace where the new formatting is noteworthy helpfull.
This feature should wait for an M1 release and have a option to disable for the case of failure.

**Comment by RedeemerSK** [comment]
> i gave this PR a try: The superbold text looks blury and hard to read :-(, otherwise it looks OK and all tests pass. image

I tried to make the method name stand out the most, so I gave it `font-weight: 800` which I thought was the most non-disruptive way (to keep consistency in text font, sizes, underlining only on link hover, etc.) ... with `font-weight: bold` it would look like this:
image
other example
image
Would that be OK or does it still make sense to try to make method name to stand out the most ?  In that case, does anyone have any other idea how to achieve it ?

 
Btw if anyone wants to play with the styling, I'm attaching 2 javadoc view browser content examples (screenshots above). Open in browser and use it's DevTools (F12) to tweak styling on-the-fly. Tip: disable `display: none` applied to checkboxes that are used to toggle enhancements to be able to toggle them.
[eclipse-javadoc-examples.zip](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/14316756/eclipse-javadoc-examples.zip)



> Please also state some examples in JDK or eclipse workspace where the new formatting is noteworthy helpfull.

Will address soon

**Comment by RedeemerSK** [comment]
> I like the idea. Have you also considered type annotations in signatures? This would be particularly interesting in the context of null annotations where implicit annotations (from `@NonNullByDefault` or from external annotations) are visualized in those hovers, too.

Nope. Also I'm not sure what exactly you have in mind. Could you please describe your idea little bit more ?
Thanks

**Comment by RedeemerSK** [comment]
Rebased onto master + changed superbold text to standard bold.

> ... This feature should wait for an M1 release **and have a option to disable for the case of failure**.

Toggle menu item added (for now added as 2nd commit, most probably will squash later). When disabled, no changes are done to generated HTML content (tags), although CSS prepended to generated HTML does contain enhancements segement that is however not used.

enhancements_toggling

Or did you @jukzi mean feature-flag instead ?

**Comment by RedeemerSK** [comment]
> I only wonder why there are so many configurations possible. I would just want to use it without ever reconfiguring it.
...
That feels a bit overpowered, also the sourcecode is a little big by that. ...

I expect the defaults will be just fine for vast majority of users without ever needing to customize settings in any way. However I did not like the idea of forcing particular configuration/coloring that I/we would decide to every user.

IMHO it makes sense to be opinionated about defaults, just not in a forceful way.

One thing I'm not 100% sure about is the need for the whole "type parameters (nesting) levels coloring". It seemed like a nice idea in the early days of prototyping. But with the arrival of type parameters references coloring (that I think is more useful and therefore preferred) + lighter text formatting for type parameters segments (to achieve visual difference even without colors) I'm less convinced someone may appreciate this option.

> @RedeemerSK Would you be able to maintain it? @jjohnstn WDYT?
Of course I am committed to do so.

**Comment by jjohnstn** [comment]
@jukzi Will review by tomorrow.

**Review by jjohnstn — CHANGES_REQUESTED** [review]
@RedeemerSK Thanks for the patch.  Playing around with it I find that:

1.  The preview is confusing and sometimes the preview box disappears on me which makes it even more confusing.   For example. I might have set always applied to type references but if I hover over type levels, the preview won't put references on.  If I hover back over type references, it still won't show it in preview.  If I select never apply, then hovering over it shows it in the preview. 
2. When I click to change styling mode it doesn't change until I move off element and come back (e.g. switching to hover mode doesn't kick in until I move off and come back).  I am seeing this in the Javadoc View
3. I think that Formatting and Wrapping should be combined and/or always on when styling is chosen.  Not sure when one would want one but not the other or when one wouldn't expect extra formatting when styling is selected.  It would simplify things and I find it rather jittery as the text moves around depending on where I am hovering.
4. Would be nice to supply help so users can understand the different settings for color modes.  It isn't intuitive what happens when both coloring modes are always on at the same time.  References wins over levels.
5. I see wrapping and formatting settings affecting the Javadoc hover in the editor but no color support.
6. IMO, the icon in the Javadoc view should toggle the option on/off and the arrow should bring up the menu.  This seems more consistent with other icons with arrows where the icon does one thing when you click on it (e.g. run the last configuration) and the menu only comes up by clicking the arrow (e.g. show all the last configurations run to choose from).
7. I am wondering if options should simply be on and off with no hover setting.  It would make it much simpler both in code and how the user sets things.  Even if there were scenarios where users would want hover-optional support, it could simply be all options chosen show up with hover instead of choosing them individually via separate settings.

**Comment by jjohnstn** [comment]
> Thanks @jjohnstn for playing with it and providing feedback.
> 
> > 1. The preview is confusing and sometimes the preview box disappears on me which makes it even more confusing.   For example. I might have set always applied to type references but if I hover over type levels, the preview won't put references on.  If I hover back over type references, it still won't show it in preview.  If I select never apply, then hovering over it shows it in the preview.
> 
> I'm aware that atm preview is not 100% bulletproof (see my reply to No.2). Although easily set right by hovering away and back over menu items (as you've already found out), I'll try to fix everything that I'll find or will be reported. But I can't reproduce preview overlay not being displayed at all when menu is open. Do you have exact steps to reproduce it ? Also what platform are you on ?
> 

I'm on Linux.  I was just flipping between options and watching the preview change.

> > 2. When I click to change styling mode it doesn't change until I move off element and come back (e.g. switching to hover mode doesn't kick in until I move off and come back).  I am seeing this in the Javadoc View
> 
> I can reproduce the "change not kicking in" only when switching from on_hover to disabled (and know exactly where to go to fix it). But when switching disabled->enabled or enabled->on_hover, I see it being applied correctly (actualy it was since you armed the menu item before selecting it to switch the mode)
> 
> > 3. I think that Formatting and Wrapping should be combined and/or always on when styling is chosen.  Not sure when one would want one but not the other or when one wouldn't expect extra formatting when styling is selected.  It would simplify things and I find it rather jittery as the text moves around depending on where I am hovering.
> 
> That's reasonable. I wasn't sure if it was right to force users to always use these 2 enhancements together, so I kept them separate ... again, with having opinionated defaults = 'enabled' for both. I thought maybe there could be users that are OK with current formatting = all text bold, but would appreciate just wrapping, because IMHO that's really game changer for methods (arguments). If you don't see this as a valid expectation, then I'll merge the two.

I don't think it is a valid expectation so yes they should be merged.  I also think it would be reasonable to have them on if styling is chosen and not if off, i.e. no option needed.  The simpler, the better.
> 
> > 4. Would be nice to supply help so users can understand the different settings for color modes.  It isn't intuitive what happens when both coloring modes are always on at the same time.  References wins over levels.
> 
> Well, first I would like to come to conclusion/agreement whether type levels coloring actually makes sense. And if decided to keep it in, then we can discuss how such help could be implemented.
> 
I wasn't sure how/why someone would use that feature which was kind of what I was hoping the documentation might provide (e.g. a solid sample that it would make sense to use it).  Anyway, I'm fine with it being removed as it would again simplify things and make the interface cleaner for the end-user.

> > 5. I see wrapping and formatting settings affecting the Javadoc hover in the editor but no color support.
> 
> Wait, does it mean coloring does not work for you at all in Javadoc hover ? Because only difference between Javadoc hover and Javadoc view is how styling menu (toolbar) button is added to GUI, everything else is completely the same. Remember, enhancements modes are not shared between the two, only color preferences are.

Not sure I understand what you mean.  When I select styling from the menu in the Javadoc view, I see the wrapping and formatting options change the text in the Javadoc pop-up that comes up when I hover over an element in the editor, but the colorization options do not affect the hover (just black text) whether I choose always applied or on hover.  Am I missing a way of setting this for the editor hover?  I assumed it was connected based on the wrapping/formatting showing up.
> 
> > 6. IMO, the icon in the Javadoc view should toggle the option on/off and the arrow should bring up the menu.  This seems more consistent with other icons with arrows where the icon does one thing when you click on it (e.g. run the last configuration) and the menu only comes up by clicking the arrow (e.g. show all the last configurations run to choose from).
> 
> Makes sense. Will prototype.

Great.
> 
> > 7. I am wondering if options should simply be on and off with no hover setting.  It would make it much simpler both in code and how the user sets things.  Even if there were _**scenarios where users would want hover-optional support, it could simply be all options chosen show up with hover**_ instead of choosing them individually via separate settings.
> 
> Remember what visual difference it makes when wrapping enhancement is switched from off to on (I think that's what you meant with "jittery" in No.3). If that would be happenning on hover, that would be quite disturbing for most user. So I think you most often don't want that one to be "on_hover", which effectively would be the case if this suggestion would be implemented. Or maybe I'm imagining what you're suggesting incorrectly.

What I'm thinking is that it would be much simpler if the menu shows check-boxes for the various enabled/disabled options and user chooses on or off by clicking.  The view changes as options change on or off.  The added feature of being able to hover over an option to preview isn't necessary and makes things more complicated than needed.
> 
> The main reason I had for implementing the hover support was that I did not want to force "rainbow content" on users by default, but still needed a quick way to enable colors if the Javadoc content would require it - eg. if non-trivial (nested and/or multiple) generics type parameters are present. So for me hover is mainly about coloring. Hover support for wrapping & formatting is just to treat all enhancements the same.

I think if someone chooses to activate the feature and chooses colorization, the "rainbow content" would be unexpected so there is no need to shield them from it.  If they don't like the colors, they can change them or turn that part of the feature off.

**Comment by RedeemerSK** [comment]
> I don't think it is a valid expectation so yes they should be merged. I also think it would be reasonable to have them on if styling is chosen and not if off, i.e. no option needed. The simpler, the better.

OK

> I wasn't sure how/why someone would use that feature which was kind of what I was hoping the documentation might provide (e.g. a solid sample that it would make sense to use it). Anyway, I'm fine with it being removed as it would again simplify things and make the interface cleaner for the end-user.

I guess I'll remove it then ... unless someone else provides valid argument for keeping it.

> Not sure I understand what you mean. When I select styling from the menu in the Javadoc view, I see the wrapping and formatting options change the text in the Javadoc pop-up that comes up when I hover over an element in the editor, but the colorization options do not affect the hover (just black text) whether I choose always applied or on hover. Am I missing a way of setting this for the editor hover? I assumed it was connected based on the wrapping/formatting showing up.

When you enter into Javadoc hover (pop-up) viewer with mouse (or press F2), then enriched viewer control is displayed where you'll see toolbar with styling menu button, through which you can toggle enhancements **specifically** for Javadoc hover and also change **settings shared** with Javadoc view (colors & button itself now being master on/of toggle)

I guess you were toggling all enhancements ("master on/off") via Javadoc view button which is right away recognisable in Javadoc hover as well, since defaults for hover are also formatting=always_on & wrapping=always_on.

> What I'm thinking is that it would be much simpler if the menu shows check-boxes for the various enabled/disabled options and user chooses on or off by clicking. The view changes as options change on or off. The added feature of being able to hover over an option to preview isn't necessary and makes things more complicated than needed.

Well, OK then. I'll prepare version with preview functionality removed.

> I think if someone chooses to activate the feature and chooses colorization, the "rainbow content" would be unexpected so there is no need to shield them from it. If they don't like the colors, they can change them or turn that part of the feature off.

Seems like other version I'll prepare will be with hover support removed as well.

**Comment by RedeemerSK** [comment]
@jjohnstn see now, all things you suggested / requested were done

Next I plan to once again look into whether it would be possible to refresh displayed JavadocHover viewer somehow after toggling enhancements on/off ... now the viewer is closed (setVisible(false)) since it's the 'display after mouse hover' code path where content is being re-created and enhancements state is applied.

But that would not bring any drastic UX improvement, since IMHO it's not a big deal that Javadoc hover viewer is closed when toggling enhancements with the styling menu button.

(toggling coloring does not close the viewer since I kept it to be just a checkbox state change in current content)
(since JavadocViewer works differently, the refresh was possible and was already implemented)

**Comment by RedeemerSK** [comment]
> Next I plan to once again look into whether it would be possible to refresh displayed JavadocHover viewer somehow after toggling enhancements on/off ... now the viewer is closed (setVisible(false)) since it's the 'display after mouse hover' code path where content is being re-created and enhancements state is applied.

Done

After that it was possible to remove realtime toggling of checkboxes inside browser content, since now (without any hover functionality) refresh of content (view) is required only after changing some settings ... which users don't do often (well, probably never).

(I don't however plan to get rid of checkboxes inside HTML & CSS alltogether even though it would be possible now that there is working full view (content) refreshing)


Now all the cool stuff is gone 😢  ... but if that had to be the price to get this thing accepted, then "goodbye my friends cool UI/UX hacks, this world was not ready for you" 😄

**Comment by jjohnstn** [comment]
Hi @RedeemerSK The new design is much simpler, thanks.  I agree that you had some cool UI/UX hacks and perhaps they can be used for something in the future.  With the latest code, I have a few comments:

1. The pull-down arrow says "Enable or Disable styling enhancements".  It should be changed to be Styling enhancements or something like it
2. The pull-down is disabled when the toggle is disabled.  It probably wouldn't hurt to enable it all the time so preferences can be changed.
3. I changed one color and then changed it back using restore defaults.  I found the following in my log: !MESSAGE Following custom color preferences were removed:
	javadocElementsStyling.typesParamsReferenceColor_1 = RGB {252, 233, 79} which may or may not be expected
4. Afterwards, the Javadoc view got locked and I can't get it to change by selecting new methods.  It is locked on one method with styling selected.  I didn't do much other than try the various settings (disabling/enabling and turning off/on colorization).  I am on Linux and was looking Collection.toArray(T[] a)

The test errors in the latest build after rebasing are of no consequence as some Java 22 constants have been added but the I-build hasn't caught up yet.

**Comment by RedeemerSK** [comment]
Hi @jjohnstn, thanks for the review

> 1. The pull-down arrow says "Enable or Disable styling enhancements".  It should be changed to be Styling enhancements or something like it

As far as I can tell SWT does not support unique tooltip text on arrow that is different from tooltip for the button, So either it stays like it is now or tooltip for the whole button will get changed or removed.

> 2. The pull-down is disabled when the toggle is disabled.  It probably wouldn't hurt to enable it all the time so preferences can be changed.

Done

> 3. I changed one color and then changed it back using restore defaults.  I found the following in my log: !MESSAGE Following custom color preferences were removed:
>    javadocElementsStyling.typesParamsReferenceColor_1 = RGB {252, 233, 79} which may or may not be expected

I added this intentionally thinking it can be useful for the user to see what colors were reset to defaults ... if they would want to go back to them (e.g. they triggered reset by accident).

Removed now.

> 4. Afterwards, the Javadoc view got locked and I can't get it to change by selecting new methods.  It is locked on one method with styling selected.  I didn't do much other than try the various settings (disabling/enabling and turning off/on colorization).  I am on Linux and was looking Collection.toArray(T[] a)

I was not able to reproduce this. If you happen to find exact steps that trigger that for you, let me know then.

However, assuming it's really my changes causing described issue, then I guess it would most probably be addition & usage of `org.eclipse.jdt.internal.ui.infoviews.JavadocView.fIgnoringNewInputOverride` that could cause new inputs of JavadocView to be ignored ... but then it should cause issue only for one single following attempt to set new input to view.

Looking at the code I can't imagine a way it could 'lock' JavadocView. Still I made one fix there (made the field volatile since it's access not only from SWT thread) but I don't expect this would fix the issue, if the issue really is related to `fIgnoringNewInputOverride`.

**Comment by RedeemerSK** [comment]
@jjohnstn  Shall I squash the commits as a preparation for merge then ? (not sure what the git hsitory preference / merge workflow here is)

**Comment by jjohnstn** [comment]
@RedeemerSK No need to squash.  I do that when I merge.  The test failure is a known flaky test.

**Review by jjohnstn — APPROVED** [review]

**Comment by jjohnstn** [comment]
@RedeemerSK Do you want to write a N&N entry and submit a PR to www.eclipse.org-eclipse or would you like me to do it?  Try and make it brief with an example.

**Comment by RedeemerSK** [comment]
> @RedeemerSK Do you want to write a N&N entry and submit a PR to [www.eclipse.org-eclipse](http://www.eclipse.org-eclipse) or would you like me to do it? Try and make it brief with an example.

Will try soon

**Comment by RedeemerSK** [comment]
@jjohnstn while preparing N&N entry I found 2 (lets call them) corner cases when types parameters coloring was not working as expected.

- Missing coloring (for classes/interfaces from other compilation unit) missing_types_coloring
- Unwanted coloring of type label(s) outside of generic signature (diamond brackets) unwanted_types_coloring

After fix
- missing_types_coloring_fix
- unwanted_types_coloring_fix



I prepared a fix ... is it fine to not make a new issue for it ? I would probably just create new branch (e.g. "issue_1073_fix") with fix commit and create PR like that if that's fine.

Thanks for reply

**Comment by iloveeclipse** [comment]
> just create new branch (e.g. "issue_1073_fix") with fix commit and create PR like that if that's fine.

Yes, please. In the commit message please refer to the original issue and/or this PR.

**Comment by RedeemerSK** [comment]
> Yes, please. In the commit message please refer to the original issue and/or this PR.
Thanks @iloveeclipse for quick reply.

PR created #1296

**Comment by RedeemerSK** [comment]
> > @RedeemerSK Do you want to write a N&N entry and submit a PR to [www.eclipse.org-eclipse](http://www.eclipse.org-eclipse) or would you like me to do it? Try and make it brief with an example.
> 
> Will try soon

@jjohnstn here it is: https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/145
And while you're at it, please take a look at #1296 as well. Thank you

**Pull request merged**
