### PR TITLE
fix icon position accordingly to UI Guidelines

### PR DESCRIPTION
**Pull request by Michael5601**
see for more information: https://github.com/eclipse-platform/eclipse.platform.images/pull/111

### CODE REVIEW

**Comment by akurtakov** [comment]
Way too many things for me to handle and I can't dedicate time for that soon.

**Comment by vogella** [comment]
@jjohnstn can you have a look?

**Comment by jjohnstn** [comment]
@vogella Will do

**Review by jjohnstn — APPROVED** [review]
LGTM

**Pull request merged**
