### PR TITLE
Updated bundles with comparator errors

### PR DESCRIPTION
**Pull request by trancexpress**
See: eclipse-platform/eclipse.platform.releng.aggregator#1923

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Feature versions need an update:
```
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.7-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.jeview.feature: Only qualifier changed for (org.eclipse.jdt.jeview.feature.feature.jar/1.1.300.v20240321-1123). Expected to have bigger x.y.z than what is available in baseline (1.1.300.v20240126-1130) -> [Help 1]
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.7-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.bcoview.feature: Only qualifier changed for (org.eclipse.jdt.bcoview.feature.feature.jar/1.2.300.v20240321-1123). Expected to have bigger x.y.z than what is available in baseline (1.2.300.v20240118-1157) -> [Help 1]
```

**Comment by trancexpress** [comment]
@iloveeclipse what is `callCodeQLworkflow` again?

**Comment by iloveeclipse** [comment]
> @iloveeclipse what is `callCodeQLworkflow` again?

Yet another github action. Is this PR based on latest master? I assume the problem is that jdt.ui depends on jdt.core that bumped some constants, but since we didn't had stable build yet, tycho can't see the latest jdt.core.

**Comment by trancexpress** [comment]
> Yet another github action. Is this PR based on latest master? I assume the problem is that jdt.ui depends on jdt.core that bumped some constants, but since we didn't had stable build yet, tycho can't see the latest jdt.core.

I'm not 100% sure, I checked out the aggregator repository and its submodules yesterday. I rebased just in case.

**Review by iloveeclipse — APPROVED** [review]
Compilation error is because we don't have stable jdt.core build yet. Locally everything works.

**Pull request merged**
