### PR TITLE
Adding the unified GH workflow to JDT UI

### PR DESCRIPTION
**Pull request by vogella**
Lets also use the commmon GH action flow like in PDE in JDT. This should help to discover issues in JDT UI faster and help to identfiy flacky tests.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by vogella** [comment]
@laeubi can you check, the common setup is your "baby" if IIRC.

**Comment by laeubi** [comment]
@vogella see
- https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/536

**Comment by vogella** [comment]
Ups sorry the replicate.

**Comment by vogella** [comment]
> @vogella you can still help making that one "work" I just left it "as-is" as there is not much interest from JDT team in apply this ...

With @akurtakov we now have a person in JDT which is interested in build automation and improvements so it might start to move. JDT seems to suffer from a lot of instability lately, I assume they start paying the price for not investing into community and code simplifications.

**Comment by vogella** [comment]
> > we now have a person in JDT which is interested in build automation and improvements
> 
> Good, finally! I assume the rest JDT committers us are simply not interested in any improvements and for sure in no automations. I would prefer you would not post such offending and insulting comments in the future.

https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/536 is from April and the contributor @laeubi said "s there is not much interest from JDT team in apply this ...".  Also JDT UI did not even have a pomless build until I contributed one yesterday. Nor does JDT core. If that means that JDT is actively working on build improvements that I fear we have a different standard for such work.

I know you fight very hard to keep the build up and stable, so sorry if you were insulted. But I do not see a lot of releng improvements from other JDT people.

> > JDT seems to suffer from a lot of instability lately
> 
> Please provide a pointer to this claim.

Just a feeling so I might be wrong here and I was under the impression that we see a lot of JDT build issues in the last days?

**Comment by iloveeclipse** [comment]
> Just a feeling so I might be wrong here and I was under the impression that we see a lot of JDT build issues in the last days?

Yes, your feelings are wrong here. The troubles we have are usual if we have ~50 PR's merged in a day right after freeze.

**Pull request closed without merging**
