### PR TITLE
Removing unnecessary themeing extension for breadcrumb (light theme)

### PR DESCRIPTION
**Pull request by mvm-sap**
## What it does

We have improved the look and feel of existing light theme in eclipse. Please refer this https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114 for further information on the same. There was a bug reported as part of this theme change, which could be found here https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114#issuecomment-2241561690. While fixing this issue we figured out that the grey background for breadcrumb is unnecessary and hence removed the light theme extension. Please find below the screenshot of how it looks with and without extension both in old and new light themes
image
image
image

## How to test

Enable breadcrumb and test the changes with old and enhanced light theme.

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by BeckerWdf** [comment]
@vogella: Aren't you a JDT comitter. Can you review and if ok merge this PR?

**Comment by vogella** [comment]
@BeckerWdf No I'm not a JDT committer, maybe @jjohnstn can review?

**Comment by BeckerWdf** [comment]
Sorry to "ping" again. Any of the JDT committers: Can you pls. review this PR?

**Comment by HannesWell** [comment]
> Sorry to "ping" again. Any of the JDT committers: Can you pls. review this PR?

Maybe @iloveeclipse, @akurtakov or @jukzi?

**Comment by jjohnstn** [comment]
@mvm-sap Sorry, I missed this.  Merged.

**Comment by BeckerWdf** [comment]
> @mvm-sap Sorry, I missed this. Merged.

Thanks for your help.

**Pull request merged**
