### PR TITLE
Improve Onboarding Icon for Java Perspectives

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by BeckerWdf** [comment]
See also https://github.com/eclipse-platform/eclipse.platform.images/pull/13

**Comment by BeckerWdf** [comment]
@iloveeclipse: I slept one night about your remarks about the icon and improved it. Can you pls. review and merge?

**Comment by iloveeclipse** [comment]
I've commented on https://github.com/eclipse-platform/eclipse.platform.images/pull/13

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
I've commented on https://github.com/eclipse-platform/eclipse.platform.images/pull/13

**Comment by BeckerWdf** [comment]
> I've commented on [eclipse-platform/eclipse.platform.images#13](https://github.com/eclipse-platform/eclipse.platform.images/pull/13)

I removed the line

**Pull request merged**
