### PR TITLE
Set up workflow for automated version increments in pull-requests

### PR DESCRIPTION
**Pull request by HannesWell**
Set up for this repository the workflow for automated version increments in pull-requests added via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2352

The EF infra team has already added the required PAT of the Platform-bot to this repo as [requested](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5020#note_2825941) via
- https://github.com/eclipse-jdt/.eclipsefdn/pull/6

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by HannesWell** [comment]
Same question as in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3021#issuecomment-2377871558.

**Comment by HannesWell** [comment]
> Same question as in [eclipse-jdt/eclipse.jdt.core#3021 (comment)](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3021#issuecomment-2377871558).

The previous behavior is now preserved exactly as it is.

@iloveeclipse can you please review this?

**Comment by HannesWell** [comment]
@iloveeclipse or @jukzi can this be completed too?

**Comment by akurtakov** [comment]
Automatic version increments are really helpful. Merging.

**Pull request merged**
