### PR TITLE
Fix NPE in QuickAssistProcessorUtil

### LINKED ISSUE #917: NPE in QuickAssistProcessorUtil isDeprecatedMethodCallWithReplacement
i was editing ` src\org\eclipse\core\tests\resources\IFileTest.java`
```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.eclipse.jdt.core.dom.TagElement.getTagName()" is null
	at org.eclipse.jdt.internal.ui.text.correction.QuickAssistProcessorUtil.isDeprecatedMethodCallWithReplacement(QuickAssistProcessorUtil.java:535)
	at org.eclipse.jdt.internal.ui.text.correction.QuickFixProcessor.process(QuickFixProcessor.java:784)
	at org.eclipse.jdt.internal.ui.text.correction.QuickFixProcessor.getCorrections(QuickFixProcessor.java:379)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor$SafeCorrectionCollector.safeRun(JavaCorrectionProcessor.java:384)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor$SafeCorrectionProcessorAccess.run(JavaCorrectionProcessor.java:342)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor$SafeCorrectionProcessorAccess.process(JavaCorrectionProcessor.java:337)
	at org.eclipse.jdt.internal.ui.text.correction.JavaCorrectionProcessor.collectCorrections(JavaCorrectionProcessor.java:470)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.getJavaAnnotationFixes(ProblemHover.java:115)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.computeCompletionProposals(ProblemHover.java:89)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover$ProblemInfo.<init>(ProblemHover.java:74)
	at org.eclipse.jdt.internal.ui.text.java.hover.ProblemHover.createAnnotationInfo(ProblemHover.java:178)
	at org.eclipse.jdt.internal.ui.text.java.hover.AbstractAnnotationHover.getHoverInfo2(AbstractAnnotationHover.java:755)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
```

### PR DESCRIPTION
**Pull request by jjohnstn**
- fixes #917
- fix API errors in JDT UI build

## What it does

Fixes NPE.

## How to test

See issue.

## Author checklist

- [X] I have thoroughly tested my changes
- [X] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [X] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Review by rgrunber — APPROVED** [review]
Looks fine to me. Reversing the check should prevent the NPE.

**Comment by jjohnstn** [comment]
Merging for RC1

**Comment by jjohnstn** [comment]
@iloveeclipse Just keeping you informed that I merged this.  There was an issue with github builds reporting API errors in JDT UI due to a Tycho change so that is what the build.properties part of the change was for.

**Comment by iloveeclipse** [comment]
Sure, I saw this and it was right to fix.

**Pull request merged**
