### PR TITLE
Enabled tests

### PR DESCRIPTION
**Pull request by amartya4256**
## What it does

Enabled some disabled tests which aren't in broken state anymore.
https://github.com/eclipse-platform/eclipse.platform/issues/525

## Author checklist

- [x ] I have thoroughly tested my changes
- [ x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by jukzi** [comment]
@iloveeclipse i accidentally pressed `update branch` button which created a merge commit. can you disable that button? see https://github.com/orgs/community/discussions/3245#discussioncomment-7339067

**Comment by iloveeclipse** [comment]
> @iloveeclipse i accidentally pressed `update branch` button which created a merge commit. can you disable that button? see https://github.com/orgs/community/discussions/3245#discussioncomment-7339067

I do not see options shown on referenced screen. 

All "merges" are disabled for this repo, yet "Update with merge" is still shown for PR's here. I believe that is exactly what the last comment on the thread youare referring to is saying.

**Comment by netomi** [comment]
I do believe this comes from the setting:

```
allow_update_branch: true
```

which will show a button in the PR if the PR branch can be updated with changes from the target branch prior to merging the PR.


The setting

```
allow_merge_commit: true
```

will affect the options that you get when you actually wanna merge the PR, but the merge commit happened before the merge to the target branch.

**Comment by jukzi** [comment]
will allow_update_branch=false still show "rebase" button?

**Comment by netomi** [comment]
No, it will not show any button anymore, so if you just wanna prevent merge commits from happening, the setting that you change will be good imho.

**Comment by jukzi** [comment]
@amartya4256 tests are green now. thanks for your contribution.

**Pull request merged**
