### PR TITLE
Move folder to jdt.core.manipulations; Replace plugin-specific references

### PR DESCRIPTION
**Pull request by robstryker**
## What it does

This patch moves a significant number of refactor classes into jdt manipulations. Twelve previous PRs have been building to this patch, moving dependency classes and small bits of logic around to prepare for this. 

By having the refactor operations available in jdt manipulations, they will be availalable to non-UI consumers such as vscode-java / jdt.ls. 

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by jjohnstn** [comment]
Hi @robstryker There was another change to ExtractTempRefactoring just merged.  You'll need to handle the conflicts above.  I fixed the build problem so it should build.

**Comment by robstryker** [comment]
@mickaelistria changed the o.e.resources api to use generics and this has broken the build via 9 warnings about generic typesafety.  I will need to fix that first.

**Review by jjohnstn — APPROVED** [review]
Looks good.

**Comment by iloveeclipse** [comment]
FYI: this caused SDK build failure, see https://github.com/eclipse-platform/eclipse.platform/issues/716.

**Comment by tjwatson** [comment]
This PR caused us to have split packages for the following:

`org.eclipse.jdt.internal.corext.refactoring.reorg`
`org.eclipse.jdt.internal.corext.refactoring`

The following classes remain in `org.eclipse.jdt.ui`

```
org/eclipse/jdt/internal/corext/refactoring/reorg/ReorgUtils.class
org/eclipse/jdt/internal/corext/refactoring/reorg/JavaElementTransfer.class
org/eclipse/jdt/internal/corext/refactoring/RefactoringAvailabilityTester.class
org/eclipse/jdt/internal/corext/refactoring/RefactoringExecutionStarter.class
```

I assume these classes could not move to `org.eclipse.jdt.core.manipulation` for good reason?  If so then we need to put some additional meta-data on the exports of these packages from `org.eclipse.jdt.core.manipulation` similar to how the `org.eclipse.core.runtime` split package is exported from `org.eclipse.equinox.registry`:

https://github.com/eclipse-equinox/equinox/blob/7eb1b42156e06225670c1c61cf351f805d5bbd13/bundles/org.eclipse.equinox.registry/META-INF/MANIFEST.MF#L11

Something like:
```
Export-Package: org.eclipse.jdt.internal.corext.refactoring; jdt.core=split;mandatory:=jdt.core,
 org.eclipse.jdt.internal.corext.refactoring.reorg; jdt.core=split;mandatory:=jdt.core,
```

**Pull request merged**
